framework:
    cache:
        default_redis_provider: 'redis://redis:6379'
        
        pools:
            stats.cache:
                adapter: cache.adapter.redis
                default_lifetime: 3600 # 1 heure en secondes 