# Read the documentation: https://github.com/FriendsOfSymfony/FOSElasticaBundle/blob/master/doc/setup.md
fos_elastica:
    clients:
        default:
            host: elasticsearch
            port: 9200
    indexes:
        products:
            properties:
                id: ~
                title: 
                    type: text
                    analyzer: french
                price:
                    type: float
                archive:
                    type: boolean
                digital:
                    type: boolean
                purchasePrice:
                    type: float
                alert:
                    type: integer
                category:
                    type: nested
                    properties:
                        id: ~
                        name: { type: text }
            persistence:
                driver: orm
                model: App\Entity\Product
                provider: ~
                finder: ~
                repository: App\Repository\ProductSearchRepository
