sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        environment: '%env(APP_ENV)%'
        release: '1.0.0'
        traces_sample_rate: 1.0
        send_default_pii: true
    tracing:
        enabled: true
        dbal:
            enabled: true
        twig:
            enabled: true 